### PR TITLE
support mongoose ^8.0.0

### PR DESCRIPTION
**Pull request by simonecorsi**
Hi, I'm successfully using this package in my `mongoose` ^8 projects and we have to use `--legacy-peer-deps` everytime, can we update this? :)

### CODE REVIEW

**Review by DScheglov — APPROVED** [review]

**Comment by DScheglov** [comment]
Hi, @simonecorsi 

thank you for PR -- I've merged it, but it seems tests fail with mongoose@8:
https://github.com/DScheglov/mongoose-schema-jsonschema/actions/runs/8247422956/job/22555515343

So, I'm going to fix this in the lib code, then I will publish a new version.

**Comment by simonecorsi** [comment]
> Hi, @simonecorsi
> 
> thank you for PR -- I've merged it, but it seems tests fail with mongoose@8: https://github.com/DScheglov/mongoose-schema-jsonschema/actions/runs/8247422956/job/22555515343
> 
> So, I'm going to fix this in the lib code, then I will publish a new version.

Ok, no hurry thank you! Let me know if there is something we can do to help!

**Comment by DScheglov** [comment]
@simonecorsi 

it was quite simple fix.
Now you can use `mongoose-schema-jsonschema@2.2.0`

**Comment by simonecorsi** [comment]
@DScheglov Thank you 🙏

**Pull request merged**
